selected_scheme scheme-full
TEXDIR /usr/local/texlive/2024
TEXMFCONFIG $user_home/.texlive2024/texmf-config
TEXMFHOME $user_home/.texlive2024/
TEXMFLOCAL /usr/local/texlive/texmf-local
TEXMFSYSCONFIG /usr/local/texlive/2024/texmf-config
TEXMFSYSVAR /usr/local/texlive/2024/texmf-var
TEXMFVAR $user_home/.texlive2024/texmf-var
binary_x86_64-linux 1