selected_scheme scheme-full
TEXDIR /usr/local/texlive/2025
TEXMFCONFIG ~/.texlive2025/texmf-config
TEXMFHOME ~/.texlive2025/
TEXMFLOCAL /usr/local/texlive/texmf-local
TEXMFSYSCONFIG /usr/local/texlive/2025/texmf-config
TEXMFSYSVAR /usr/local/texlive/2025/texmf-var
TEXMFVAR ~/.texlive2025/texmf-var
binary_x86_64-linux 1
TEXLIVE_INSTALL_NO_CONTEXT_CACHE 1
