:PROPERTIES:
:ID:       e4c9f06e-7b48-4778-bae2-c63506922f5d
:END:
#+title: Installation and configuration of Rclone
#+filetags: :backup:rclone:sync:

The following are Instructions to configure the backup program Rclone on [[id:c3cf1e06-fdb1-42a8-bebd-cddae74dd1b6][Debian]]
* Installation
[[[https://rclone.org/downloads/][Download links]]]
#+begin_src bash
  wget https://downloads.rclone.org/v1.68.2/rclone-v1.68.2-linux-amd64.deb
#+end_src

#+begin_src bash
   curl https://rclone.org/install.sh | sudo bash
   #+end_src
**  Script
#+begin_src bash :dir "/sudo::"
    # Check https://rclone.org/downloads/ for the latest version
    rclone_url="https://downloads.rclone.org/v1.68.2/rclone-v1.68.2-linux-amd64.deb"
    cd "$idownload" || exit
    if [ ! -f rclone.deb ]; then
        wget --tries=2 --retry-connrefused --waitretry=10 ${rclone_url} -O rclone.deb
    fi

    if ! dpkg -l | grep -q rclone; then
        sudo dpkg -i rclone.deb
    fi
  #+end_src
* Making your own client ID
Should allow faster transfer rates
** How to create your own Google Drive client ID for rclone:
[[https://rclone.org/drive/#making-your-own-client-id][Official instructions]]
1) Log into the [[https://console.developers.google.com/][Google API Console]] with your Google account. It doesn't matter what Google account you use. (It need not be the same account as the Google Drive you want to access)

2) Select a project or create a new project.

3) Under "ENABLE APIS AND SERVICES" search for "Drive", and enable the "Google Drive API".

4) Click "Credentials" in the left-side panel (not "Create credentials", which opens the wizard), then "Create credentials"

5) If you already configured an "Oauth Consent Screen", then skip to the next step; if not, click on "CONFIGURE CONSENT SCREEN" button (near the top right corner of the right panel), then select "External" and click on "CREATE"; on the next screen, enter an "Application name" ("rclone" is OK); enter "User Support Email" (your own email is OK); enter "Developer Contact Email" (your own email is OK); then click on "Save" (all other data is optional). Click again on "Credentials" on the left panel to go back to the "Credentials" screen.

   - (PS: if you are a GSuite user, you could also select "Internal" instead of "External" above, but this will restrict API use to Google Workspace users in your organisation).

6) Click on the "+ CREATE CREDENTIALS" button at the top of the screen, then select "OAuth client ID".

7) Choose an application type of "Desktop app" and click "Create". (the default name is fine)

8) It will show you a client ID and client secret. Make a note of these.

   - (If you selected "External" at Step 5 continue to "Publish App" in the Steps 9 and 10. If you chose "Internal" you don't need to publish and can skip straight to Step 11.)

9) Go to "Oauth consent screen" and press "Publish App"

10) Click "OAuth consent screen", then click "PUBLISH APP" button and confirm, or add your account under "Test users".

11) Provide the noted client ID and client secret to rclone.

** How to create Client ID for OneDrive Personal
[[https://rclone.org/onedrive/#getting-your-own-client-id-and-key][Official instructions]]
1) Open https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade and then click New registration.
2) Enter a name for your app, choose account type
   - =Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)=, select Web in Redirect URI, then type (do not copy and paste) http://localhost:53682/ and click Register. Copy and keep the Application (client) ID under the app name for later use.
3) Under manage select =Certificates & secrets=, click =New client secret=. Enter a description (can be anything) and set Expires to 24 months. Copy and keep that secret Value for later use (you won't be able to see this value afterwards).
4) Under manage select API permissions, click Add a permission and select =Microsoft Graph= then select =Delegated permissions=.
5) Search and select the following permissions: =Files.Read=, =Files.ReadWrite=, =Files.Read.All=, =Files.ReadWrite.All=, =offline_access=, =User.Read= and =Sites.Read.All= (if custom access scopes are configured, select the permissions accordingly). Once selected click Add permissions at the bottom.


* Back-links
[[[id:c3cf1e06-fdb1-42a8-bebd-cddae74dd1b6][Programs]]]
